set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports change_left]
set_property IOSTANDARD LVCMOS33 [get_ports change_mode]
set_property IOSTANDARD LVCMOS33 [get_ports change_right]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports ring]
set_property IOSTANDARD LVCMOS33 [get_ports setting]
set_property IOSTANDARD LVCMOS33 [get_ports switch0]
set_property IOSTANDARD LVCMOS33 [get_ports switch1]
set_property PACKAGE_PIN W19 [get_ports change_left]
set_property PACKAGE_PIN U18 [get_ports change_mode]
set_property PACKAGE_PIN T17 [get_ports change_right]
set_property PACKAGE_PIN W5 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
set_property PACKAGE_PIN T18 [get_ports reset]
set_property PACKAGE_PIN L1 [get_ports ring]
set_property PACKAGE_PIN U17 [get_ports setting]
set_property PACKAGE_PIN E19 [get_ports {state[1]}]
set_property PACKAGE_PIN W16 [get_ports switch0]
set_property PACKAGE_PIN V16 [get_ports switch1]
set_property PACKAGE_PIN U16 [get_ports {state[0]}]
set_property PACKAGE_PIN W4 [get_ports {AN[3]}]
set_property PACKAGE_PIN V4 [get_ports {AN[2]}]
set_property PACKAGE_PIN U4 [get_ports {AN[1]}]
set_property PACKAGE_PIN U2 [get_ports {AN[0]}]
set_property PACKAGE_PIN W7 [get_ports {seven_seg[6]}]
set_property PACKAGE_PIN W6 [get_ports {seven_seg[5]}]
set_property PACKAGE_PIN U8 [get_ports {seven_seg[4]}]
set_property PACKAGE_PIN V8 [get_ports {seven_seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seven_seg[2]}]
set_property PACKAGE_PIN V5 [get_ports {seven_seg[1]}]
set_property PACKAGE_PIN U7 [get_ports {seven_seg[0]}]
##Pmod Header JB
##Sch name = JB1
set_property PACKAGE_PIN K17 [get_ports {pmod_1}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_1}]
##Sch name = JB2
set_property PACKAGE_PIN M18 [get_ports {pmod_2}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_2}]
##Sch name = JB3
#set_property PACKAGE_PIN B15 [get_ports ]
#set_property IOSTANDARD LVCMOS33 [get_ports ]
##Sch name = JB4
set_property PACKAGE_PIN P18 [get_ports {pmod_4}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_4}]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

